import { ingestMessage, IngestInput } from "../mail/ingest";
import { config } from "../config";

const hoursAgo = (h: number) => new Date(Date.now() - h * 60 * 60 * 1000);

type Spec = Omit<IngestInput, "uid" | "folder" | "toAddresses" | "ccAddresses"> & {
  to?: string[];
};

function specs(): Spec[] {
  const me = config.emailUser || "you@aol.com";

  return [
    {
      messageId: "demo-1@family.example",
      fromName: "Mom",
      fromAddress: "mom@example.com",
      to: [me],
      subject: "Re: Sunday dinner?",
      date: hoursAgo(2),
      bodyText: "Hi honey, are you still coming Sunday? Let me know what time works. Love, Mom",
      bodyHtml: "",
      hasAttachments: false,
      seen: false,
      flagged: false,
      listUnsubscribeHeader: null,
      listUnsubscribePostHeader: null,
      listId: null,
      precedenceBulk: false,
    },
    {
      messageId: "demo-2@coworker.example",
      fromName: "Priya Shah",
      fromAddress: "priya.shah@example.com",
      to: [me],
      subject: "Notes from today's sync",
      date: hoursAgo(5),
      bodyText: "Attaching notes from the meeting. Can you review before Friday?",
      bodyHtml: "",
      hasAttachments: true,
      seen: false,
      flagged: false,
      listUnsubscribeHeader: null,
      listUnsubscribePostHeader: null,
      listId: null,
      precedenceBulk: false,
    },
    {
      messageId: "demo-3@wayfair.example",
      fromName: "Wayfair Deals",
      fromAddress: "deals@email.wayfair.example",
      to: [me],
      subject: "Flash Sale: 60% OFF furniture this weekend only!",
      date: hoursAgo(6),
      bodyText: "Shop now and save big. Limited time offer, free shipping on orders over $35.",
      bodyHtml:
        '<p>Shop now! <a href="https://email.wayfair.example/unsubscribe?id=abc">Unsubscribe</a></p>',
      hasAttachments: false,
      seen: false,
      flagged: false,
      listUnsubscribeHeader:
        "<https://email.wayfair.example/unsubscribe?id=abc>, <mailto:unsub@wayfair.example?subject=unsubscribe>",
      listUnsubscribePostHeader: "List-Unsubscribe=One-Click",
      listId: null,
      precedenceBulk: true,
    },
    {
      messageId: "demo-4@bankofexample.com",
      fromName: "Bank of Example",
      fromAddress: "alerts@bankofexample.com",
      to: [me],
      subject: "Your statement is ready to view",
      date: hoursAgo(10),
      bodyText: "Your July statement is now available. Log in to your account to view it.",
      bodyHtml: "",
      hasAttachments: false,
      seen: true,
      flagged: false,
      listUnsubscribeHeader: null,
      listUnsubscribePostHeader: null,
      listId: null,
      precedenceBulk: false,
    },
    {
      messageId: "demo-5@facebookmail.example",
      fromName: "Facebook",
      fromAddress: "notification@facebookmail.example",
      to: [me],
      subject: "You have 3 new notifications",
      date: hoursAgo(11),
      bodyText: "See what you missed on Facebook.",
      bodyHtml: '<a href="https://facebookmail.example/unsub/xyz">Unsubscribe</a>',
      hasAttachments: false,
      seen: false,
      flagged: false,
      listUnsubscribeHeader: "<https://facebookmail.example/unsub/xyz>",
      listUnsubscribePostHeader: null,
      listId: null,
      precedenceBulk: true,
    },
    {
      messageId: "demo-6@amazon.example",
      fromName: "Amazon",
      fromAddress: "shipment-tracking@amazon.example",
      to: [me],
      subject: "Your package has shipped",
      date: hoursAgo(14),
      bodyText: "Your order #112-2938 has shipped and will arrive Thursday. Track your package.",
      bodyHtml: "",
      hasAttachments: false,
      seen: true,
      flagged: false,
      listUnsubscribeHeader: null,
      listUnsubscribePostHeader: null,
      listId: null,
      precedenceBulk: false,
    },
    {
      messageId: "demo-7@neighborhoodgroup.example",
      fromName: "Riverdale Neighbors Digest",
      fromAddress: "digest@groups.google.com",
      to: [me],
      subject: "[Riverdale Neighbors] Daily Digest",
      date: hoursAgo(16),
      bodyText: "12 new messages today in Riverdale Neighbors group.",
      bodyHtml: "",
      hasAttachments: false,
      seen: false,
      flagged: false,
      listUnsubscribeHeader:
        "<mailto:riverdale-neighbors+unsubscribe@groups.google.com>",
      listUnsubscribePostHeader: null,
      listId: "<riverdale-neighbors.groups.google.com>",
      precedenceBulk: true,
    },
    {
      messageId: "demo-8@bestbuy.example",
      fromName: "Best Buy",
      fromAddress: "offers@email.bestbuy.example",
      to: [me],
      subject: "Exclusive offer: $50 off laptops this week",
      date: hoursAgo(20),
      bodyText: "Don't miss this deal. Shop laptops and save.",
      bodyHtml: '<a href="https://email.bestbuy.example/unsub?id=1">unsubscribe</a>',
      hasAttachments: false,
      seen: false,
      flagged: false,
      listUnsubscribeHeader: "<https://email.bestbuy.example/unsub?id=1>",
      listUnsubscribePostHeader: null,
      listId: null,
      precedenceBulk: true,
    },
    {
      messageId: "demo-9@lottery-scam.example",
      fromName: "International Prize Committee",
      fromAddress: "claims@intl-prize-notice.example",
      to: [me],
      subject: "CONGRATULATIONS YOU HAVE WON $2,500,000!!!",
      date: hoursAgo(22),
      bodyText:
        "CONGRATULATIONS YOU HAVE WON the international lottery! Click here now to claim your prize via wire transfer.",
      bodyHtml: "",
      hasAttachments: false,
      seen: false,
      flagged: false,
      listUnsubscribeHeader: null,
      listUnsubscribePostHeader: null,
      listId: null,
      precedenceBulk: false,
    },
    {
      messageId: "demo-10@linkedin.example",
      fromName: "LinkedIn",
      fromAddress: "messages-noreply@linkedin.example",
      to: [me],
      subject: "You appeared in 9 searches this week",
      date: hoursAgo(28),
      bodyText: "See who's been looking at your profile.",
      bodyHtml: "",
      hasAttachments: false,
      seen: true,
      flagged: false,
      listUnsubscribeHeader: "<https://linkedin.example/unsub/9182>",
      listUnsubscribePostHeader: "List-Unsubscribe=One-Click",
      listId: null,
      precedenceBulk: true,
    },
    {
      messageId: "demo-11@friend.example",
      fromName: "Jordan Lee",
      fromAddress: "jordan.lee@example.com",
      to: [me],
      subject: "Photos from the trip!",
      date: hoursAgo(30),
      bodyText: "Finally uploaded them, check out the album.",
      bodyHtml: "",
      hasAttachments: true,
      seen: false,
      flagged: true,
      listUnsubscribeHeader: null,
      listUnsubscribePostHeader: null,
      listId: null,
      precedenceBulk: false,
    },
    {
      messageId: "demo-12@airline.example",
      fromName: "SkyWay Airlines",
      fromAddress: "noreply@skyway.example",
      to: [me],
      subject: "Booking confirmation: Flight to Denver",
      date: hoursAgo(36),
      bodyText: "Your itinerary is confirmed. Flight 442 departs 8:15am on Aug 2.",
      bodyHtml: "",
      hasAttachments: true,
      seen: true,
      flagged: false,
      listUnsubscribeHeader: null,
      listUnsubscribePostHeader: null,
      listId: null,
      precedenceBulk: false,
    },
    {
      messageId: "demo-13@storenewsletter.example",
      fromName: "Cozy Home Newsletter",
      fromAddress: "newsletter@cozyhome.example",
      to: [me],
      subject: "This week's newsletter: fall decor ideas",
      date: hoursAgo(40),
      bodyText: "Our latest newsletter is here with fall decorating inspiration.",
      bodyHtml: '<a href="https://cozyhome.example/preferences">manage subscription</a>',
      hasAttachments: false,
      seen: false,
      flagged: false,
      listUnsubscribeHeader: null,
      listUnsubscribePostHeader: null,
      listId: null,
      precedenceBulk: false,
    },
  ];
}

/** Populates (or refreshes) the local cache with realistic sample mail so
 * the whole app can be exercised without live AOL credentials. Safe to call
 * repeatedly (ingestMessage upserts on message_id). */
export function seedDemoData(): number {
  const me = config.emailUser || "you@aol.com";
  let count = 0;
  for (const spec of specs()) {
    ingestMessage({
      ...spec,
      uid: count + 1,
      folder: "INBOX",
      toAddresses: spec.to ?? [me],
      ccAddresses: [],
    });
    count += 1;
  }
  return count;
}
